{{- if .Values.workflowService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wf-service.fullname" . }}
  labels:
    {{- include "wf-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wf-service.fullname" . }}
  minReplicas: {{ .Values.workflowService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workflowService.autoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 60
        periodSeconds: 3
      - type: Pods
        value: 4
        periodSeconds: 3
      selectPolicy: Max
  metrics:
    {{- if .Values.workflowService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workflowService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.workflowService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.workflowService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
