{{- if .Values.workflowService.ingress.enabled -}}
{{- $fullName := include "wf-service.fullname" . -}}
{{- $svcPort := .Values.workflowService.service.port -}}
{{- $pathtype := .Values.workflowService.ingress.pathtype -}}
{{- $ingressPath := .Values.workflowService.ingress.path }}
{{- if and .Values.workflowService.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.workflowService.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.workflowService.ingress.annotations "kubernetes.io/ingress.class" .Values.workflowService.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wf-service.labels" . | nindent 4 }}
  annotations: {{- range .Values.workflowService.ingress.annotations }}
  {{. | indent 2 }}{{- end }}
spec:
  {{- if .Values.workflowService.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.workflowService.ingress.className | quote }}
  {{- end }}
{{- if .Values.workflowService.ingress.tls }}
  tls:
  {{- range .Values.workflowService.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{ end }}
  rules:
  {{- range .Values.workflowService.ingress.hosts }}
  - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
  {{ end }}
{{ end }}
