{{- $name := .Release.Name }}
{{- $namespace:= .Release.Namespace }}
{{- if .Values.postgresqlself }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "wf-service.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
    labels:
      app: {{ include "wf-service.fullname" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.applicationConfig }}
  {{- if (eq "BACKOFFICE_CORS_ORIGIN" $key) }}
  {{ $key }} : {{ $name }}-backoffice.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if (eq "WORKFLOW_DASHBOARD_CORS_ORIGIN" $key) }}
  {{ $key }} : {{ $name }}-workflows-dashboard.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if (eq "HEADLESS_EXAMPLE_CORS_ORIGIN" $key) }}
  {{ $key }} : {{ $name }}-headless-example.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if (eq "KYB_EXAMPLE_CORS_ORIGIN" $key) }}
  {{ $key }} : {{ $name }}-kyb-app.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}