{{- $name := .Release.Name }}
{{- $namespace:= .Release.Namespace }}
{{- $postgresqlUser := "admin" -}}
{{- $postgresqlPassword := "admin" -}}
{{- $postgresqlDatabase := "admin" -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "wf-service.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
    labels:
      app: {{ include "wf-service.fullname" . }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.applicationConfig }}
  {{- if (eq "BACKOFFICE_CORS_ORIGIN" $key) }}
  {{ $key }} : backoffice.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if (eq "WORKFLOW_DASHBOARD_CORS_ORIGIN" $key) }}
  {{ $key }} : workflows-dashboard.{{ $namespace }}.svc.cluster.local:80
  {{- end }}
  {{- if (eq "DB_URL" $key) }}
  {{ $key }}: postgres://{{ $postgresqlUser }}:{{ $postgresqlPassword }}@{{ $name }}-postgresql.{{ $namespace }}.svc.cluster.local:5432/{{ $postgresqlDatabase }}
  {{- end }}
  {{- if (eq "DB_USER" $key) }}
  {{ $key }}: {{ $postgresqlUser }}
  {{- end }}
  {{- if (eq "DB_PASSWORD" $key) }}
  {{ $key }}: {{ $postgresqlPassword }}
  {{- end }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}