version: '3'
services:
  db:
    image: sibedge/postgres-plv8:15.6-3.2.2
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres15:/var/lib/postgresql/data
volumes:
  postgres15: ~
