version: '3'
services:
  ballerine-case-managment:
    build:
      context: ../apps/backoffice-v2/
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${BACKOFFICE_PORT}:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-headless-example:
    build:
      context: ../examples/headless-example
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${HEADLESS_SVC_PORT}:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-kyb-app:
    build:
      context: ../apps/kyb-app
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${KYB_APP_PORT}:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-workflow-service:
    build:
      context: ../services/workflows-service/
      args:
        NPM_LOG_LEVEL: notice
    command:
      - /bin/sh
      - -c
      - |
        npm run db:init
        dumb-init npm run prod
    ports:
      - ${WORKFLOW_SVC_PORT}:${WORKFLOW_SVC_PORT}
    env_file: 
      - .env
    depends_on:
      ballerine-postgres:
        condition: service_healthy
    restart: on-failure
  ballerine-workflows-dashboard:
    build:
      context: ../apps/workflows-dashboard
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${WORKFLOW_DASHBOARD_PORT}:80
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-websocket-service:
    build:
      context: ../services/websocket-service
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - ${WEBSOCKET_SVC_PORT}:${WEBSOCKET_SVC_PORT}
    depends_on:
      - ballerine-workflow-service
    restart: on-failure
  ballerine-postgres:
    image: sibedge/postgres-plv8:15.3-3.1.7
    ports:
      - ${DB_PORT:-5432}:${DB_PORT-5432}
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER:-admin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-admin}"
      POSTGRES_DB: "${DB_NAME:-db}"
    volumes:
      - postgres15:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -q
        - -d
        - ${DB_NAME:-db}
        - -U
        - ${DB_USER:-admin}
      timeout: 45s
      interval: 10s
      retries: 10
volumes:
  postgres15: ~
