{{- if .Values.headlessexample.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.headlessexample.nameOverride }}
    namespace: {{ .Release.Namespace | quote }}
    labels:
      app: {{ .Values.headlessexample.nameOverride }}
spec:
    replicas: 3
    {{- if .Values.headlessexample.strategyType }}
    strategy:
      type: {{ .Values.headlessexample.strategyType }}
    {{- end }}
    {{- if .Values.headlessexample.updateStrategy }}
      rollingUpdate:
        {{- if .Values.headlessexample.updateStrategy.maxSurge }}
        maxSurge: {{ .Values.headlessexample.updateStrategy.maxSurge}}
        {{- end }}
        {{- if .Values.headlessexample.updateStrategy.maxUnavailable }}
        maxUnavailable: {{ .Values.headlessexample.updateStrategy.maxUnavailable }}
        {{- end }}
    {{- end }}
    selector:
        matchLabels:
            app: {{ .Values.headlessexample.nameOverride }}
    template:
        metadata:
            labels:
                app: {{ .Values.headlessexample.nameOverride }}
        spec:
          volumes:
          - name: example-volume
            persistentVolumeClaim:
              claimName: example-claim
          containers:
            - name: headlessexample
            {{- with .Values.nodeSelector }}
            nodeSelector:
            {{- toYaml . | nindent 8 }}
            {{- end }}
            containers:
            - name: {{ .Values.headlessexample.nameOverride }}
              image: "{{ .Values.headlessexample.image.registry }}/{{ .Values.headlessexample.image.repository }}:{{ .Values.headlessexample.image.tag }}"
              imagePullPolicy: {{ .Values.headlessexample.image.pullPolicy }}
              command: ["sh", "-c", "echo 'Hello from the headlessexample container'"]
              env:
                - name: ENV_VARIABLE_NAME
                  value: ENV_VARIABLE_VALUE
          volumeMounts:
            - name: example-volume
deadlePath: /path/to/deadle
            {{- if .Values.headlessexample.image.pullSecrets}}
            imagePullSecrets:
              - name: {{ .Values.headlessexample.image.pullSecrets }}
            {{- end }}
{{- end }}
