replicaCount: 1
restartPolicy: Always
image:
  registry: ghcr.io
  repository: ballerine-io/workflows-service
  pullPolicy: Always
  tag: "dev"
  command: [ "dumb-init", "npm", "run", "prod" ]

env: {}
envFrom: []
secrets: []

strategyType: RollingUpdate
updateStrategy:
  maxSurge: 1
  maxUnavailable: '0'

migration: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: 
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: []
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []

deploymentStrategy:
  type: "RollingUpdate"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

applicationConfig: {}

postgresqlself: false