name: Create Rebase PR from Dev to SB
permissions:
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - blokh/feat/automatic-pr-generation

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "sb"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Rebase dev to sb"
