name: CI

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      # Run this pipeline only if there are changes in specified path
      - "apps/**"
      - "services/**"
      - "examples/**"
      - "experiments/**"
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: actions/checkout@v3

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Format
        uses: actions/checkout@v3

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: echo 'Build'

  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spellcheck
        uses: ./.github/actions/spell-check-action

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo 'Test'

  test_windows:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: echo 'Unit Test'
